NUMPY INTRODUCTION

- It is a python Library designed for scientific computation
- NumPy arrays are the main reason to use NumPy Library
- It is really fast compared to ordinary python List
- It is fast because it has binding with C programing language

1D array == vectors
2D array == matrix
nD array == tensor

In [1]:
import numpy as np

In [2]:
a = [1,2,3,4,5,6]

### The block of code below will throw error, as we cannot perform square on all the elements of lost together by simply using exponent operator. The problem can be resolved using numpy array

In [3]:
a**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [ ]:
b = np.array(a)

In [ ]:
b #1D array

### So here we converted our list into a numpy array and stored it in b, now using same simple exponent function we can square all the elements of our array.

In [ ]:
b**2

### Below is the method to create numpy array using arange function, arange comprises of two words array and range, so with this we can create array without passing a list to numpy array instead we will provide the upper limit to arange numpy function. This will create 1D array from starting from zero to one less than value of upper limit provided. Array b and c are created such way only.

In [ ]:
b = np.arange(16)
c = np.array(range(16))

In [4]:
b,c

NameError: name 'b' is not defined

### In case we want our 1D array to start from 1 or any number other than zero, we can pass that value to numpy arange like we use range function in python.

In [5]:
z = np.arange(1,10)
z

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### here we are using start, stop(upper limit) and step all three like we do in range to create numpy 1D array

In [6]:
r = np.arange(2,20,2)
r

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
a= np.array(range(1,10,0.1))

TypeError: 'float' object cannot be interpreted as an integer

### From the above code we can see that the range function can not take the floating point value and throws an error but when given same floating value to numpy arange, it works.

In [8]:
b = np.arange(1,10,0.1)
b

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1,
       6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4,
       7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7,
       8.8, 8.9, 9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

### Linspace and Logspace(generated number to log base 10) are numpy functions that are used to generate equally spaced numbers between the given start and end point. By default it generates 50 numbers, we can change the value according to the numbers we need.

In [9]:
np.linspace(1,10)       #1 is start and 10 is stop both inclusive, by default these values are inclusive incase we dont
                        #want stop value to be included we can give endpoint= False within function, can be seen in 
                        #documentation.

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [10]:
a=np.linspace(1,10,10) #Have specified the number of values to be generated as 10 rather than keeping it default as 50.
a

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [11]:
np.linspace(1,10,10,endpoint=False)       # keeping endpoint=False wouldn't include endpoint
                                          # Remember 10 is not step,it is the changed value of num which is by default 50

array([1. , 1.9, 2.8, 3.7, 4.6, 5.5, 6.4, 7.3, 8.2, 9.1])

In [12]:
np.logspace(1,10)                        #by default it will generate 50 numbers to the base 10 

array([1.00000000e+01, 1.52641797e+01, 2.32995181e+01, 3.55648031e+01,
       5.42867544e+01, 8.28642773e+01, 1.26485522e+02, 1.93069773e+02,
       2.94705170e+02, 4.49843267e+02, 6.86648845e+02, 1.04811313e+03,
       1.59985872e+03, 2.44205309e+03, 3.72759372e+03, 5.68986603e+03,
       8.68511374e+03, 1.32571137e+04, 2.02358965e+04, 3.08884360e+04,
       4.71486636e+04, 7.19685673e+04, 1.09854114e+05, 1.67683294e+05,
       2.55954792e+05, 3.90693994e+05, 5.96362332e+05, 9.10298178e+05,
       1.38949549e+06, 2.12095089e+06, 3.23745754e+06, 4.94171336e+06,
       7.54312006e+06, 1.15139540e+07, 1.75751062e+07, 2.68269580e+07,
       4.09491506e+07, 6.25055193e+07, 9.54095476e+07, 1.45634848e+08,
       2.22299648e+08, 3.39322177e+08, 5.17947468e+08, 7.90604321e+08,
       1.20679264e+09, 1.84206997e+09, 2.81176870e+09, 4.29193426e+09,
       6.55128557e+09, 1.00000000e+10])

In [13]:
np.logspace(1,10,10)                #here it is generating 10 numbers only

array([1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05, 1.e+06, 1.e+07, 1.e+08,
       1.e+09, 1.e+10])

In [14]:
np.logspace(1,10,10,base=2)        #by default base has been changed to 2

array([   2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,  512.,
       1024.])

In [15]:
np.linspace(1,10,15,endpoint=False) , 9/15

(array([1. , 1.6, 2.2, 2.8, 3.4, 4. , 4.6, 5.2, 5.8, 6.4, 7. , 7.6, 8.2,
        8.8, 9.4]), 0.6)

### Trying to generate numbers as power of 2 using list and doing same using numpy. Former is throwing error whereas later is not.

In [16]:
2**list(range(4))

TypeError: unsupported operand type(s) for ** or pow(): 'int' and 'list'

In [17]:
2**np.linspace(1,10,10) #each value generated from linspace function is raised as power of 2

array([   2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,  512.,
       1024.])

In [18]:
2**np.arange(1,5)

array([ 2,  4,  8, 16], dtype=int32)

### Note number of sqaure bracket denotes the dimension of an array, one pair of square bracket mean 1D array, two pair of square bracket mean 2D and three pair mean 3D array.

In [19]:
b                   #array that we generated in line number 9

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1,
       6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4,
       7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7,
       8.8, 8.9, 9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

### Below is the method to read the documentation of any function

In [20]:
b.itemsize?

In [21]:
b.shape,b.dtype,b.itemsize    #checking for shape datatype and itemsize of array b

((90,), dtype('float64'), 8)

In [22]:
np.empty((2,2,2))

array([[[0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 4.32801506e-321],
        [1.11258446e-306, 6.23059725e-307]]])

In [23]:
np.ones((2,5,))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [24]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
a=np.arange(1,17)
b=np.arange(100,116)

In [26]:
a,b

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16]),
 array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
        113, 114, 115]))

In [27]:
a.shape

(16,)

In [28]:
a.shape=(4,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [29]:
a.reshape(2,2,4)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [30]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [31]:
x=b.reshape(-1,2,1).shape

In [32]:
b.resize(4,4)

In [33]:
b

array([[100, 101, 102, 103],
       [104, 105, 106, 107],
       [108, 109, 110, 111],
       [112, 113, 114, 115]])

In [34]:
b.resize(16,2)

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

In [35]:
np.resize(b,(8))

array([100, 101, 102, 103, 104, 105, 106, 107])

In [36]:
np.reshape?

In [37]:
np.resize?

In [38]:
b.shape=(1,2,4,1,2)

In [39]:
b.T.shape,np.transpose(b).shape

((2, 1, 4, 2, 1), (2, 1, 4, 2, 1))

In [40]:
np.swapaxes(b,1,3).shape

(1, 1, 4, 2, 2)

In [41]:
np.swapaxes?

### Other way to create array and then have performed slicing on it. Slicing is grabing required elements from the array.

In [42]:
list1=[1,2,3,4,5]

In [43]:
list2=[6,7,8,9,10]

In [44]:
list3=[11,12,13,14,15]

In [45]:
x=np.array([list1,list2,list3])

In [46]:
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

### Slicing format is [start of row : stop of row , start of column : stop of column] in case start is not specified by default is first that is zeroeth index row, and similary stop will be last one same goes for column.

In [47]:
x[1:,2:4]

array([[ 8,  9],
       [13, 14]])

In [48]:
x.reshape(1,15)  #this reshape can be done as there were 15 elements in array x and is reshaped into size of 
                 #15 elements only

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [49]:
type(x)

numpy.ndarray

In [50]:
np.rollaxis(b,3,0).shape

(1, 1, 2, 4, 2)

In [51]:
b.shape = (4,2,2)

In [52]:
b

array([[[100, 101],
        [102, 103]],

       [[104, 105],
        [106, 107]],

       [[108, 109],
        [110, 111]],

       [[112, 113],
        [114, 115]]])

In [53]:
np.expand_dims(b,axis=-1).shape

(4, 2, 2, 1)

In [54]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

### Slicing syntax again : a[ row start : row stop : row step , column start : column stop : column step ]

In [55]:
a[[0,2,3],::2]

array([[ 1,  3],
       [ 9, 11],
       [13, 15]])

In [57]:
a[[1,3]]        #this is the way to call rows or column by their index number directly when slicing has no pattern

array([[ 5,  6,  7,  8],
       [13, 14, 15, 16]])

In [59]:
a[a>5]         #grabing numbers greater than 5 from matrix a

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [61]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [63]:
np.where(a%2==0,'even','odd')    #where is like replace, condition, if condition satisfies then this else that

array([['odd', 'even', 'odd', 'even'],
       ['odd', 'even', 'odd', 'even'],
       ['odd', 'even', 'odd', 'even'],
       ['odd', 'even', 'odd', 'even']], dtype='<U4')

### Difference between Ravel and Flatten, though both return 1D array is flatten always returns a copy and ravel return a view of original array, thus ravel is faster as no memory is occupied.

In [64]:
c=np.ravel(a)

In [65]:
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [70]:
d=np.ones((3,2,3))

In [71]:
d

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [74]:
e=np.ravel(d)  #So clearly we can see ravel is used to return 1D array

In [75]:
e

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1.])

In [81]:
d

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [82]:
d.flatten()

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1.])

In [83]:
np.where(d%2==0,'even','odd')

array([[['odd', 'odd', 'odd'],
        ['odd', 'odd', 'odd']],

       [['odd', 'odd', 'odd'],
        ['odd', 'odd', 'odd']],

       [['odd', 'odd', 'odd'],
        ['odd', 'odd', 'odd']]], dtype='<U4')

In [84]:
d

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [85]:
np.ravel(d)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1.])

In [88]:
a=np.array([1,2,3,4,5])